<?php

namespace Ei\einstitutBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Critere_has_preconisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriterePreconisationRepository extends EntityRepository
{
    
    public function PreconisationFiche($id)
    {
        $em = $this->getEntityManager();
        
        $query = $em->createQuery('SELECT c FROM EieinstitutBundle:criterepreconisation c 
                                JOIN c.preconisation p 
                                WHERE p.fiche_preconisation = :idfiche ')
                    ->setParameter("idfiche", $id);
        $oCrit_Preconisations = $query->getResult();
        return $oCrit_Preconisations ;
        
    }
    
}
