<?php

namespace Ei\einstitutBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementsRepository extends EntityRepository
{
}
