parameters:
#    eieinstitut.example.class: Ei\einstitutBundle\Example

services:
#    eieinstitut.example:
#        class: %eieinstitut.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
