<?php

namespace Proxies\__CG__\Ei\einstitutBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Listes extends \Ei\einstitutBundle\Entity\Listes implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setListesBaseContacts(\Doctrine\Common\Collections\ArrayCollection $values)
    {
        $this->__load();
        return parent::setListesBaseContacts($values);
    }

    public function getListesBaseContacts()
    {
        $this->__load();
        return parent::getListesBaseContacts();
    }

    public function addListesBaseContacts($value)
    {
        $this->__load();
        return parent::addListesBaseContacts($value);
    }

    public function removeListesBaseContacts($value)
    {
        $this->__load();
        return parent::removeListesBaseContacts($value);
    }

    public function setListesEnvoye(\Doctrine\Common\Collections\ArrayCollection $values)
    {
        $this->__load();
        return parent::setListesEnvoye($values);
    }

    public function getListesEnvoye()
    {
        $this->__load();
        return parent::getListesEnvoye();
    }

    public function addListesEnvoye($value)
    {
        $this->__load();
        return parent::addListesEnvoye($value);
    }

    public function removeListesEnvoye($value)
    {
        $this->__load();
        return parent::removeListesEnvoye($value);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'listes_base_contact', 'listes_envoye');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}