<?php

namespace Proxies\__CG__\Ei\einstitutBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Tags extends \Ei\einstitutBundle\Entity\Tags implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setTag(\Doctrine\Common\Collections\ArrayCollection $values)
    {
        $this->__load();
        return parent::setTag($values);
    }

    public function getTag()
    {
        $this->__load();
        return parent::getTag();
    }

    public function addTag($value)
    {
        $this->__load();
        return parent::addTag($value);
    }

    public function removeTag($value)
    {
        $this->__load();
        return parent::removeTag($value);
    }

    public function setTagTutoriel(\Doctrine\Common\Collections\ArrayCollection $values)
    {
        $this->__load();
        return parent::setTagTutoriel($values);
    }

    public function getTagTutoriel()
    {
        $this->__load();
        return parent::getTagTutoriel();
    }

    public function addTagTutoriel($value)
    {
        $this->__load();
        return parent::addTagTutoriel($value);
    }

    public function removeTagTutoriel($value)
    {
        $this->__load();
        return parent::removeTagTutoriel($value);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLibelle($libelle)
    {
        $this->__load();
        return parent::setLibelle($libelle);
    }

    public function getLibelle()
    {
        $this->__load();
        return parent::getLibelle();
    }

    public function setEtat($etat)
    {
        $this->__load();
        return parent::setEtat($etat);
    }

    public function getEtat()
    {
        $this->__load();
        return parent::getEtat();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'libelle', 'etat', 'tag', 'tag_tutoriel');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}