<?php

namespace Proxies\__CG__\Ei\einstitutBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TutorielsEnLigne extends \Ei\einstitutBundle\Entity\TutorielsEnLigne implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getTypeTutoriel()
    {
        $this->__load();
        return parent::getTypeTutoriel();
    }

    public function setTypeTutoriel($u2)
    {
        $this->__load();
        return parent::setTypeTutoriel($u2);
    }

    public function getUserTuto()
    {
        $this->__load();
        return parent::getUserTuto();
    }

    public function setUserTuto($u2)
    {
        $this->__load();
        return parent::setUserTuto($u2);
    }

    public function setTutorielsEnLigneTags(\Doctrine\Common\Collections\ArrayCollection $values)
    {
        $this->__load();
        return parent::setTutorielsEnLigneTags($values);
    }

    public function getTutorielsEnLigneTags()
    {
        $this->__load();
        return parent::getTutorielsEnLigneTags();
    }

    public function addTutorielsEnLigneTags($value)
    {
        $this->__load();
        return parent::addTutorielsEnLigneTags($value);
    }

    public function removeTutorielsEnLigneTags($value)
    {
        $this->__load();
        return parent::removeTutorielsEnLigneTags($value);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setDescriptif($descriptif)
    {
        $this->__load();
        return parent::setDescriptif($descriptif);
    }

    public function getDescriptif()
    {
        $this->__load();
        return parent::getDescriptif();
    }

    public function setDateDebut($dateDebut)
    {
        $this->__load();
        return parent::setDateDebut($dateDebut);
    }

    public function getDateDebut()
    {
        $this->__load();
        return parent::getDateDebut();
    }

    public function setDateFin($dateFin)
    {
        $this->__load();
        return parent::setDateFin($dateFin);
    }

    public function getDateFin()
    {
        $this->__load();
        return parent::getDateFin();
    }

    public function setStatut($statut)
    {
        $this->__load();
        return parent::setStatut($statut);
    }

    public function getStatut()
    {
        $this->__load();
        return parent::getStatut();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'descriptif', 'dateDebut', 'dateFin', 'statut', 'type_tutoriel', 'user_tuto', 'tutoriel_enligne_tag');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}